import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px # Using Plotly for better aesthetics and interactive charts in Streamlit

# --- 1. DATA DEFINITIONS ---

# Disaster Data (32 types total)
DISASTER_DATA = [
    {'name': 'Floods & Drainage', 'category': 'water', 'description': 'Caused by heavy rainfall and inadequate river capacity, a major issue in most river basins.'},
    {'name': 'Cyclones', 'category': 'water', 'description': 'Tropical storms affecting India\'s long coastline with severe winds, rain, and storm surges.'},
    {'name': 'Droughts', 'category': 'water', 'description': 'Caused by deficient rainfall, affecting vast agricultural areas and water supplies.'},
    {'name': 'Tornadoes & Hurricanes', 'category': 'water', 'description': 'Violent rotating columns of air causing localized, intense damage.'},
    {'name': 'Hailstorms', 'category': 'water', 'description': 'Precipitation in the form of ice, damaging crops and property.'},
    {'name': 'Cloud Burst', 'category': 'water', 'description': 'An extreme amount of precipitation in a short period of time.'},
    {'name': 'Heat & Cold Wave', 'category': 'water', 'description': 'Periods of abnormally hot or cold weather that can have severe public health impacts.'},
    {'name': 'Snow Avalanches', 'category': 'water', 'description': 'Rapid flow of snow down a slope, a major hazard in Himalayan regions.'},
    {'name': 'Sea Erosion', 'category': 'water', 'description': 'The wearing away of coastal land by sea action.'},
    {'name': 'Thunder & Lightning', 'category': 'water', 'description': 'Electrical storms that can cause fires, deaths, and power outages.'},
    {'name': 'Tsunami', 'category': 'water', 'description': 'Series of large ocean waves generated by undersea earthquakes or landslides.'},
    {'name': 'Landslides & Mudflows', 'category': 'geological', 'description': 'Down-slope movement of rock, debris, or earth, common in Himalayan and Ghat regions.'},
    {'name': 'Earthquakes', 'category': 'geological', 'description': 'Sudden shaking of the ground caused by seismic waves, with high risk in Himalayan areas.'},
    {'name': 'Dam Failure / Bursts', 'category': 'geological', 'description': 'Catastrophic failure of a dam structure leading to downstream flooding.'},
    {'name': 'Mine Disasters', 'category': 'geological', 'description': 'Accidents occurring in mines, including collapses, floods, and explosions.'},
    {'name': 'Chemical & Industrial', 'category': 'chemical', 'description': 'Disasters from process failures, spills, or explosions at industrial plants.'},
    {'name': 'Nuclear Disasters', 'category': 'chemical', 'description': 'Accidents at nuclear facilities leading to the release of radioactive material.'},
    {'name': 'Forest Fires', 'category': 'accident', 'description': 'Uncontrolled fires in forests, posing a threat to flora, fauna, and human settlements.'},
    {'name': 'Urban Fires', 'category': 'accident', 'description': 'Major fires in urban areas, including residential and commercial buildings.'},
    {'name': 'Mine Flooding', 'category': 'accident', 'description': 'Inundation of underground mines with water, trapping miners.'}, 
    {'name': 'Oil Spills', 'category': 'accident', 'description': 'Release of liquid petroleum hydrocarbon into the environment, causing ecological damage.'},
    {'name': 'Major Building Collapse', 'category': 'accident', 'description': 'Structural failure of large buildings, often in urban areas.'},
    {'name': 'Serial Bomb Blasts', 'category': 'accident', 'description': 'A series of coordinated terrorist bombings.'},
    {'name': 'Festival Related Disasters', 'category': 'accident', 'description': 'Accidents such as stampedes or fires occurring during large festive gatherings.'},
    {'name': 'Electrical Disasters', 'category': 'accident', 'description': 'Major accidents caused by electrical failures or short circuits.'},
    {'name': 'Air, Road & Rail Accidents', 'category': 'accident', 'description': 'Large-scale transportation accidents resulting in significant casualties.'},
    {'name': 'Boat Capsizing', 'category': 'accident', 'description': 'Overturning of boats, often due to overcrowding or bad weather.'},
    {'name': 'Village Fire', 'category': 'accident', 'description': 'Fires that spread through rural villages, often with flammable housing materials.'},
    {'name': 'Biological Disasters', 'category': 'biological', 'description': 'Outbreaks of infectious diseases like epidemics and pandemics.'},
    {'name': 'Pest Attacks', 'category': 'biological', 'description': 'Widespread crop destruction caused by insects or other pests, like locust swarms.'},
    {'name': 'Cattle Epidemics', 'category': 'biological', 'description': 'Widespread disease outbreaks among livestock, such as foot-and-mouth disease.'},
    {'name': 'Food Poisoning', 'category': 'biological', 'description': 'Mass incidents of illness caused by consumption of contaminated food.'}
]

# Data for the Distribution Chart
CHART_DATA = pd.DataFrame({
    'Category': ['Water & Climate', 'Geological', 'Chemical & Industrial', 'Accident-Related', 'Biological'],
    'Types': [11, 4, 2, 11, 4]
})

# Data for the DM Cycle and Framework
CYCLE_STEPS = {
    'Prevention': 'Measures to avoid the occurrence of a disaster altogether or to reduce its potential impact.',
    'Mitigation': 'Actions taken to reduce the severity or consequences of a disaster, such as building codes and zoning.',
    'Preparedness': 'Planning, training, and educational activities for events that cannot be mitigated.',
    'Response': 'Actions taken immediately before, during, or directly after a disaster to save lives and meet basic human needs.',
    'Rehabilitation': 'Actions to restore affected communities to their proper, pre-disaster level of functioning.',
    'Reconstruction': 'The process of rebuilding communities, including "building back better" to be more resilient.'
}

# --- 2. STREAMLIT APP LAYOUT & STYLING ---

# Set wide layout and title
st.set_page_config(
    page_title="Disaster Management in India",
    layout="wide",
    initial_sidebar_state="auto"
)

# Injecting Custom CSS for a better look (Creamy background, custom headers, card styling)
st.markdown(
    """
    <style>
    /* Main body background and font */
    .stApp {
        background-color: #FDFBF8; /* Off-white/Creamy background */
        color: #3f3f46; /* Gray-700 for text */
        font-family: 'Inter', sans-serif;
    }
    
    /* Custom main header */
    .main-header {
        font-size: 2.5em;
        font-weight: 800;
        color: #c2410c; /* Orange-700 */
        text-align: center;
        padding-top: 1rem;
    }
    
    /* Custom subheaders for sections */
    .subheader {
        font-size: 2em;
        font-weight: 700;
        color: #1f2937; /* Darker text for titles */
        margin-top: 2rem;
        margin-bottom: 1rem;
        border-bottom: 3px solid #f97316; /* Orange border */
        padding-bottom: 0.5rem;
    }
    
    /* Custom styling for the "cards" in the Disaster Types section */
    .disaster-card {
        background-color: white;
        padding: 15px;
        border-radius: 8px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        margin-bottom: 15px;
        border-left: 5px solid #fb923c; /* Light Orange accent */
    }
    .disaster-card h4 {
        color: #c2410c;
        font-weight: 600;
        margin-bottom: 5px;
    }
    
    /* Custom styling for key metrics boxes */
    .metric-box {
        background-color: white;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
        margin-bottom: 20px;
    }
    .metric-value {
        font-size: 3em !important;
        font-weight: bold;
        color: #ea580c !important; /* Orange-600 */
    }
    
    /* Make Streamlit buttons orange */
    div[data-baseweb="radio"] label {
        border-radius: 20px !important;
        padding: 8px 12px !important;
        transition: background-color 0.3s;
    }
    div[data-baseweb="radio"] label:hover {
        background-color: #ffe4c4;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# Header and Introduction
st.markdown('<div class="main-header">DM in India: An Interactive Dashboard</div>', unsafe_allow_html=True)
st.markdown(
    """
    <p style='text-align: center; max-width: 900px; margin: 0 auto 2rem;'>
    India's unique geo-climatic conditions make it vulnerable to a wide range of natural and man-made disasters. 
    The **High Power Committee on Disaster Management** identified 32 distinct types. 
    This dashboard provides an interactive exploration of these hazards and the robust framework established to manage them.
    </p>
    """, unsafe_allow_html=True
)

st.divider()

# --- 3. OVERVIEW SECTION ---
st.markdown('<h2 class="subheader" id="overview">1. Overview of India\'s Disaster Landscape</h2>', unsafe_allow_html=True)

# Container for Overview layout
overview_container = st.container()

with overview_container:
    col1, col2 = st.columns([1, 1])

    with col1:
        st.markdown("### Key Vulnerabilities")
        
        # Using custom metric boxes for better visual appeal
        st.markdown(
            """
            <div class='metric-box'>
                <p class='text-xl text-gray-500'>Drought Prone Agricultural Land</p>
                <p class='metric-value text-orange-600'>68%</p>
                <p class='text-sm text-gray-600'>Risk to food security due to deficient rainfall.</p>
            </div>
            """, unsafe_allow_html=True
        )
        st.markdown(
            """
            <div class='metric-box'>
                <p class='text-xl text-gray-500'>Coastline exposed to Cyclones</p>
                <p class='metric-value text-blue-600'>7,516 km</p>
                <p class='text-sm text-gray-600'>Major coastal threat from tropical storms and storm surges.</p>
            </div>
            """, unsafe_allow_html=True
        )
        st.markdown(
            """
            <div class='metric-box'>
                <p class='text-xl text-gray-500'>Seismic Zones (High Risk)</p>
                <p class='metric-value text-red-600'>4 Zones</p>
                <p class='text-sm text-gray-600'>The Himalayan region is particularly vulnerable to high-intensity earthquakes.</p>
            </div>
            """, unsafe_allow_html=True
        )

    with col2:
        st.markdown("### Disaster Categories Breakdown (32 Types)")
        
        # Using Plotly for a visually modern Doughnut Chart
        fig = px.pie(
            CHART_DATA, 
            values='Types', 
            names='Category', 
            hole=.4, # Makes it a doughnut chart
            color_discrete_sequence=px.colors.qualitative.T10 # Use a clean color palette
        )
        fig.update_traces(textposition='inside', textinfo='percent+label')
        fig.update_layout(showlegend=True)
        st.plotly_chart(fig, use_container_width=True)
        
        st.info("The 32 disaster types are grouped into 5 categories for holistic risk assessment.")

st.divider()

# --- 4. DISASTER TYPES SECTION ---
st.markdown('<h2 class="subheader" id="types">2. Explore Disaster Types</h2>', unsafe_allow_html=True)
st.markdown("Select a category below to filter and learn about the **32 specific disaster types** identified by the national framework.")

# Filter component
filter_choice = st.radio(
    "Filter by Category:",
    options=['all', 'water', 'geological', 'chemical', 'accident', 'biological'],
    format_func=lambda x: x.replace('_', ' ').title() if x != 'all' else 'All Types (32)',
    horizontal=True,
    key="disaster_filter"
)

# Filtering logic
if filter_choice == 'all':
    filtered_data = DISASTER_DATA
else:
    filtered_data = [d for d in DISASTER_DATA if d['category'] == filter_choice]

st.markdown(f"**Showing {len(filtered_data)} Disaster Types:**")

# Display filtered data using custom styled cards in columns
num_cols = 4 
cols = st.columns(num_cols) 
col_index = 0

for item in filtered_data:
    with cols[col_index]:
        # Inject the custom styled HTML card
        st.markdown(
            f"""
            <div class='disaster-card'>
                <h4>{item['name']}</h4>
                <p style='font-size: 0.85rem; color: #52525b;'>{item['description']}</p>
            </div>
            """, 
            unsafe_allow_html=True
        )
    
    col_index = (col_index + 1) % num_cols # Move to the next column


st.divider()

# --- 5. MANAGEMENT FRAMEWORK SECTION ---
st.markdown('<h2 class="subheader" id="framework">3. India\'s Disaster Management Framework</h2>', unsafe_allow_html=True)
st.markdown(
    """
    India has shifted from a reactive, relief-centric approach to a proactive and holistic one focused on prevention, 
    mitigation, and preparedness. Explore the key components of this strategy below.
    """
)

# Use Streamlit tabs for the Framework content
tab1, tab2 = st.tabs(["DM Cycle (Process)", "Policy, Act & Agencies"])

with tab1:
    st.subheader("The Continuous Disaster Management Cycle")
    st.markdown("Disaster management is a continuous loop. Click on any step to focus on its role.")
    
    # Use 3 columns for 6 steps, wrapping the content
    cycle_cols = st.columns(3)
    
    for i, (step, description) in enumerate(CYCLE_STEPS.items()):
        col = cycle_cols[i % 3]
        
        with col:
            with st.container():
                st.markdown(f"#### {step}")
                st.info(description)


with tab2:
    st.subheader("Policy, Legislation, and Institutional Structure")
    
    # Nesting TABS/EXPANDER inside the main tab for clean organization
    policy_tab, act_tab, agency_tab = st.tabs(["National Policy", "DM Act, 2005", "Key Agencies"])
    
    with policy_tab:
        st.markdown("### Vision")
        st.write("To build a safe and disaster-resilient India by developing a holistic, proactive, multi-disaster oriented, and technology-driven strategy.")
        st.markdown("### Core Objectives")
        st.markdown("""
        * Promote a culture of **prevention, preparedness, and resilience**.
        * Encourage mitigation measures based on technology and traditional wisdom.
        * Mainstream disaster management into development planning.
        * Ensure efficient response and relief, especially for vulnerable sections.
        """)
        
    with act_tab:
        st.markdown("### Purpose")
        st.write("Provides the institutional and legal framework for disaster management across India, establishing a clear chain of command.")
        st.markdown("### Institutional Structure")
        st.markdown("""
        * **National Disaster Management Authority (NDMA):** Chaired by the Prime Minister. Lays down policies, plans, and guidelines.
        * **State Disaster Management Authority (SDMA):** Chaired by the Chief Minister.
        * **District Disaster Management Authority (DDMA):** Headed by the District Collector.
        """)
        
    with agency_tab:
        st.markdown("### Primary Responsibility")
        st.write("While States have the primary responsibility, the Central Government provides logistical and financial support.")
        
        st.markdown("### Key National Bodies")
        st.markdown("""
        * **Ministry of Home Affairs (DM Division):** Coordinates all central government efforts for disaster risk reduction.
        * **National Disaster Response Force (NDRF):** A specialized force for responding to disaster situations.
        * **National Institute of Disaster Management (NIDM):** Focuses on training, research, and capacity development.
        """)

st.divider()

st.markdown("---")
st.markdown("<p style='text-align: center; color: #9ca3af;'>An Interactive Dashboard on Disaster Management in India.</p>", unsafe_allow_html=True)

